# Just gives your app a name. Think of it as a name tag. Used for logging and later when multiple microservices talk to each other.
spring.application.name=patient-service

server.port=5000

# H2 Console
# enabled=true ? turns ON a built-in browser UI so you can see and query your database visually
# path=/h2-console ? sets the URL path to reach it, so you go to http://localhost:5000/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource
# url=jdbc:h2:mem:testdb ? tells Spring where the database is
# jdbc = the protocol (like https but for databases)
# h2 = the database type
# mem = in-memory, meaning the database lives in RAM and is wiped every time you restart the app
# testdb = the name of the database
# driver-class-name ? the Java class that knows how to talk to H2. Think of it as a translator between your app and the database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin_viewer
spring.datasource.password=password

# JPA
# database-platform ? tells Hibernate (the JPA engine) to use H2-specific SQL syntax. Different databases speak slightly different SQL dialects, so this sets the right one
# ddl-auto=create ? every time the app starts, Hibernate automatically creates the tables from your Java @Entity classes. The word create means it drops and recreates tables on every restart
    # Other options exist: update (keeps data), validate (just checks), none (do nothing)
# defer-datasource-initialization=true ? It tells Spring: "wait for Hibernate to finish creating tables BEFORE running data.sql". Without this your data.sql inserts would run on an empty database and fail silently
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

# SQL init
# Tells Spring to always run your data.sql file on every startup. This is what seeds your database with the 15 patient records. If this was never, your data.sql would be ignored completely.
spring.sql.init.mode=always

logging.level.root=info